### ISSUE TITLE
关于tf.image.decode_jpeg(features['image_raw'])颜色通道问题

### ISSUE THREAD

**Issue by ghost** [Ecohnoch/Tiny-Face-Recognition#1]
请问，使用tf.image.decode_jpeg(features['image_raw'])解码之后的颜色通道是r,g,b的吗？我在网上没有搜到相关的解答。

**Comment by Finn-Fengming** [comment]
是的，这里主要是不破坏原Insightface中作者的结构，具体的讨论在他那的issues里有。


------------------ 原始邮件 ------------------
发件人: goodgoodstudy92 <notifications@github.com>
发送时间: 2019年5月29日 15:15
收件人: Ecohnoch/Tiny-Face-Recognition <Tiny-Face-Recognition@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: 回复：[Ecohnoch/Tiny-Face-Recognition] 关于tf.image.decode_jpeg(features['image_raw'])颜色通道问题 (#1)




请问，使用tf.image.decode_jpeg(features['image_raw'])解码之后的颜色通道是r,g,b的吗？我在网上没有搜到相关的解答。

**Comment by ghost** [comment]
好的，谢谢
