### ISSUE TITLE
验证集预处理部分的流程代码?

### ISSUE THREAD

**Issue by lixiaoming0017** [Ecohnoch/Tiny-Face-Recognition#2]
您好,在博客里看到了您关于insightface训练的讲解,关于验证集合的数据预处理部分代码,您方便发送给我吗?我的邮箱是lvyingxia@163.com

**Comment by Finn-Fengming** [comment]
你好，可以参考这部分代码：https://github.com/deepinsight/insightface/blob/master/src/data/lfw2pack.py




------------------ 原始邮件 ------------------
发件人: "lixiaoming0017"<notifications@github.com>;
发送时间: 2019年9月4日(星期三) 上午9:30
收件人: "Ecohnoch/Tiny-Face-Recognition"<Tiny-Face-Recognition@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Ecohnoch/Tiny-Face-Recognition] 验证集预处理部分的流程代码? (#2)




您好,在博客里看到了您关于insightface训练的讲解,关于验证集合的数据预处理部分代码,您方便发送给我吗?我的邮箱是lvyingxia@163.com
