### ISSUE TITLE
匹配度：0.99999994

### ISSUE THREAD

**Issue by fanjunzhi** [Ecohnoch/Tiny-Face-Recognition#3]
人脸一：Mon-Sep--9-12-57-08-2019_1568003478114.jpg
人脸二：Mon-Sep--9-12-57-08-2019_1568003478114.jpg

![image](https://user-images.githubusercontent.com/7076712/64504310-8fa69d80-d301-11e9-867d-1de951585343.png)

**Comment by Finn-Fengming** [comment]
毕竟这是两张一模一样的图像。。。。匹配度肯定很高呀
